export const governorates = [
    { label: 'القاهرة', value: 'cairo' },
    { label: 'الجيزة', value: 'giza' },
    { label: 'الإسكندرية', value: 'alexandria' },
    { label: 'الدقهلية', value: 'dakahlia' },
    { label: 'البحر الأحمر', value: 'red sea' },
    { label: 'البحيرة', value: 'beheira' },
    { label: 'الفيوم', value: 'fayoum' },
    { label: 'الغربية', value: 'gharbia' },
    { label: 'الإسماعيلية', value: 'ismailia' },
    { label: 'المنوفية', value: 'menofia' },
    { label: 'المنيا', value: 'minya' },
    { label: 'القليوبية', value: 'qalyubia' },
    { label: 'الأقصر', value: 'luxor' },
    { label: 'بورسعيد', value: 'port said' },
    { label: 'قنا', value: 'qena' },
    { label: 'شمال سيناء', value: 'north sinai' },
    { label: 'سوهاج', value: 'sohag' },
    { label: 'جنوب سيناء', value: 'south sinai' },
    { label: 'السويس', value: 'suez' },
    { label: 'أسوان', value: 'aswan' },
    { label: 'أسيوط', value: 'assiut' },
    { label: 'بني سويف', value: 'beni suef' },
    { label: 'دمياط', value: 'damietta' },
    { label: 'الشرقية', value: 'sharqia' },
    { label: 'كفر الشيخ', value: 'kafr el sheikh' },
    { label: 'مطروح', value: 'matrouh' },
    { label: 'الوادي الجديد', value: 'new valley' }
];